= terraform-pagerduty-service
:!toc-title:
:!toc-placement:
:toc:

// TODO: Write a sentence about what this module is for
This module creates a PagerDuty service with an CloudWatch integration and outputs an SNS topic arn you can publish alarms to.
For a full example of usage, see link:examples/main.tf[].

toc::[]

== About
// TODO: Write what this module does and what problem it solves
Exposes an SNS topic you can send Cloudwatch alarms to, relayed to a Pagerduty service alarm for your team.

== Usage

To use this module, add it to your terraform!

*Note on Escalation Policy*:

- You will have to choose an existing or create a new escalation policy found in https://vyutv.pagerduty.com
- A team will be associated with an escalation policy

*After Creation*:

By default, incidents will get names from the cloudwatch alarm name. This is not a good descriptive name.
Instead, make sure to always derive the name of the incidents from the alarm description

* Go to your newly created service -> Click on "Integrations" tab
* Click on settings icon for "Amazon Cloudwatch"
* Edit Integration -> Edit "Derive name from" to "Alarm Description"
// TODO: Add variables to the module example!

[source,hcl]
----
module "traffic_notifier_api_errors_pagerduty_service" {
  source = "github.com/nsbno/terraform-pagerduty-alarm?ref=x.y.z"

  service_name = "Traffic Notifier"
  sub_name     = "Excessive API Errors"
  description  = "Error when API is having errors"

  # Use existing or create your escalation policy in Pagerduty website
  escalation_policy_name = "Test Escalation Policy"
}
----

