= terraform-pagerduty-service
:!toc-title:
:!toc-placement:
:toc:

This modules exposes an SNS topic you can send Cloudwatch alarms to, relayed to a Pagerduty service alarm for your team.

toc::[]


== Usage

[IMPORTANT] 
Remember to use the link:https://github.com/nsbno/terraform-pagerduty-provider-setup[Pagerduty Provider Setup]

*Note on Escalation Policy*:

- You will have to choose an existing or create a new escalation policy found in https://vyutv.pagerduty.com/escalation_policies
- A team will be associated with an escalation policy

*Note on Business Service*:

- Optional to define

- You will have to choose an existing or create a new escalation policy found in https://vyutv.pagerduty.com/business-services

*After Creation*:

By default, incidents will get names from the CloudWatch alarm name. This is not a good descriptive name.
Instead, make sure to always derive the name of the incidents from the alarm description

Guide with images can be found on link:https://vygruppen.atlassian.net/wiki/spaces/DEVPLATFORM/pages/6909329424/Application+Alerting#How-to-Derive-Name-from-Description[Confluence]

* Go to your PagerDuty Service Directory and find the newly created service
* Click on "Integrations" tab
* Click on settings icon for "Amazon Cloudwatch"
* Edit Integration -> Edit "Derive name from" to "Alarm Description" 
** Requires `manager` role or higher
// TODO: Add variables to the module example!

[source,hcl]
----
module "pagerduty_token" {
  source = "github.com/nsbno/terraform-pagerduty-provider-setup?ref=x.y.z"
}

provider "pagerduty" {
  token = module.pagerduty_token.token
}

module "traffic_notifier_api_errors_pagerduty_service" {
  source = "github.com/nsbno/terraform-pagerduty-alarm?ref=x.y.z"

  service_name = "Traffic Notifier"
  sub_name     = "Excessive API Errors"
  description  = "Error when API is having errors"

  # Use existing or create your escalation policy in Pagerduty website
  escalation_policy_name = "Test Escalation Policy"
}
----

== Example
link:examples/main.tf[Full example]::
Check this for a full example of how to set up Pagerduty.

== Relevant Repositories

You can use these repos together with this repo!

link:https://github.com/nsbno/terraform-aws-alarms[`nsbno/terraform-aws-alarms`]::
Get ready set up CloudWatch alarms for a variety of usecases.
Just plug in the SNS topic from this module, and you'll be set and ready to go!
